//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace renstech.NET.SupernovaDispatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("renstech.NET.SupernovaDispatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon audio_volume {
            get {
                object obj = ResourceManager.GetObject("audio_volume", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon audio_volume_low {
            get {
                object obj = ResourceManager.GetObject("audio_volume_low", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background1 {
            get {
                object obj = ResourceManager.GetObject("background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon backward {
            get {
                object obj = ResourceManager.GetObject("backward", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Backward_64 {
            get {
                object obj = ResourceManager.GetObject("Backward_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bullet_orange {
            get {
                object obj = ResourceManager.GetObject("bullet_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bullet_white {
            get {
                object obj = ResourceManager.GetObject("bullet_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap call_inbound {
            get {
                object obj = ResourceManager.GetObject("call_inbound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap call_outbound {
            get {
                object obj = ResourceManager.GetObject("call_outbound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Callhistory {
            get {
                object obj = ResourceManager.GetObject("Callhistory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon cancel_48 {
            get {
                object obj = ResourceManager.GetObject("cancel_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon cog_edit {
            get {
                object obj = ResourceManager.GetObject("cog_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Decrease {
            get {
                object obj = ResourceManager.GetObject("Decrease", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete_64 {
            get {
                object obj = ResourceManager.GetObject("delete_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon enable {
            get {
                object obj = ResourceManager.GetObject("enable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon file_list {
            get {
                object obj = ResourceManager.GetObject("file_list", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon forward {
            get {
                object obj = ResourceManager.GetObject("forward", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Forward_64 {
            get {
                object obj = ResourceManager.GetObject("Forward_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon group_edit {
            get {
                object obj = ResourceManager.GetObject("group_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap group_next {
            get {
                object obj = ResourceManager.GetObject("group_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap group_previous {
            get {
                object obj = ResourceManager.GetObject("group_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hold {
            get {
                object obj = ResourceManager.GetObject("hold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请确认是否删除所有通话记录？ 的本地化字符串。
        /// </summary>
        internal static string IDS_CALLHISTORY_DELETE_ALL {
            get {
                return ResourceManager.GetString("IDS_CALLHISTORY_DELETE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空闲 的本地化字符串。
        /// </summary>
        internal static string IDS_CHANNEL_IDLE {
            get {
                return ResourceManager.GetString("IDS_CHANNEL_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道 的本地化字符串。
        /// </summary>
        internal static string IDS_CHANNEL_NAME {
            get {
                return ResourceManager.GetString("IDS_CHANNEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认是否退出系统？ 的本地化字符串。
        /// </summary>
        internal static string IDS_CONFIRM_QUIT {
            get {
                return ResourceManager.GetString("IDS_CONFIRM_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string IDS_CONFIRM_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("IDS_CONFIRM_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该分机号码已经存在 的本地化字符串。
        /// </summary>
        internal static string IDS_ERR_EXT_EXIST {
            get {
                return ResourceManager.GetString("IDS_ERR_EXT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string IDS_ERROR_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("IDS_ERROR_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件删除失败！ 的本地化字符串。
        /// </summary>
        internal static string IDS_FILE_DELETE_FAILURE {
            get {
                return ResourceManager.GetString("IDS_FILE_DELETE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全体用户 的本地化字符串。
        /// </summary>
        internal static string IDS_GROUP_ALLUSER {
            get {
                return ResourceManager.GetString("IDS_GROUP_ALLUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义组 的本地化字符串。
        /// </summary>
        internal static string IDS_GROUP_CUSTOMIZED {
            get {
                return ResourceManager.GetString("IDS_GROUP_CUSTOMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息无法保存到服务器，请检查系统设置或网络连接！ 的本地化字符串。
        /// </summary>
        internal static string IDS_GROUP_EDITTING_DENIED {
            get {
                return ResourceManager.GetString("IDS_GROUP_EDITTING_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他组 的本地化字符串。
        /// </summary>
        internal static string IDS_GROUP_OTHER {
            get {
                return ResourceManager.GetString("IDS_GROUP_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同组名，请重新编辑！ 的本地化字符串。
        /// </summary>
        internal static string IDS_GROUPNAMEEXISTS_CONTENT {
            get {
                return ResourceManager.GetString("IDS_GROUPNAMEEXISTS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名已存在 的本地化字符串。
        /// </summary>
        internal static string IDS_GROUPNAMEEXISTS_TITLE {
            get {
                return ResourceManager.GetString("IDS_GROUPNAMEEXISTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左手柄 的本地化字符串。
        /// </summary>
        internal static string IDS_HANDSET_LEFT {
            get {
                return ResourceManager.GetString("IDS_HANDSET_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右手柄 的本地化字符串。
        /// </summary>
        internal static string IDS_HANDSET_RIGHT {
            get {
                return ResourceManager.GetString("IDS_HANDSET_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆用户名或密码错误。 的本地化字符串。
        /// </summary>
        internal static string IDS_LOGIN_ERR {
            get {
                return ResourceManager.GetString("IDS_LOGIN_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主扬声器 的本地化字符串。
        /// </summary>
        internal static string IDS_MAIN_SPEAKER {
            get {
                return ResourceManager.GetString("IDS_MAIN_SPEAKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认是否删除所有消息？ 的本地化字符串。
        /// </summary>
        internal static string IDS_MESSAGE_DELETE_ALL {
            get {
                return ResourceManager.GetString("IDS_MESSAGE_DELETE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息接收方 : {0} {1} 的本地化字符串。
        /// </summary>
        internal static string IDS_MESSAGE_DEST_FORMAT {
            get {
                return ResourceManager.GetString("IDS_MESSAGE_DEST_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NIDS服务器（{0}）连接失败。 的本地化字符串。
        /// </summary>
        internal static string IDS_NIDS_SERVER_ERROR_FORMAT {
            get {
                return ResourceManager.GetString("IDS_NIDS_SERVER_ERROR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广播 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_BROADCAST {
            get {
                return ResourceManager.GetString("IDS_PREFIX_BROADCAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_CONF {
            get {
                return ResourceManager.GetString("IDS_PREFIX_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_EAVESDROP {
            get {
                return ResourceManager.GetString("IDS_PREFIX_EAVESDROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寻呼 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_FINDCALL {
            get {
                return ResourceManager.GetString("IDS_PREFIX_FINDCALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强拆 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_INTERCEPTE {
            get {
                return ResourceManager.GetString("IDS_PREFIX_INTERCEPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组呼 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_PAGE {
            get {
                return ResourceManager.GetString("IDS_PREFIX_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强插 的本地化字符串。
        /// </summary>
        internal static string IDS_PREFIX_THREEWAY {
            get {
                return ResourceManager.GetString("IDS_PREFIX_THREEWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组信息同步失败！ 的本地化字符串。
        /// </summary>
        internal static string IDS_PRIVATE_GROUP_SYNC_ERR {
            get {
                return ResourceManager.GetString("IDS_PRIVATE_GROUP_SYNC_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认是否删除所有录音文件？ 的本地化字符串。
        /// </summary>
        internal static string IDS_RECORD_DELETE_ALL_CONTENT {
            get {
                return ResourceManager.GetString("IDS_RECORD_DELETE_ALL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录音文件删除 的本地化字符串。
        /// </summary>
        internal static string IDS_RECORD_DELETE_ALL_TITLE {
            get {
                return ResourceManager.GetString("IDS_RECORD_DELETE_ALL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法查找到该用户！ 的本地化字符串。
        /// </summary>
        internal static string IDS_SEARCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_SEARCH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息保存失败 的本地化字符串。
        /// </summary>
        internal static string IDS_SERVER_DISCONNECTED {
            get {
                return ResourceManager.GetString("IDS_SERVER_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件激活成功！ 的本地化字符串。
        /// </summary>
        internal static string IDS_SOFTWARE_ACTIVATE {
            get {
                return ResourceManager.GetString("IDS_SOFTWARE_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件激活码不正确！ 的本地化字符串。
        /// </summary>
        internal static string IDS_SOFTWARE_ACTIVATE_FAILURE {
            get {
                return ResourceManager.GetString("IDS_SOFTWARE_ACTIVATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广播调度系统 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_DAVINCI {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_DAVINCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 初始化失败！ 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_INIT_FAIL_FORMAT {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_INIT_FAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安防中心 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_SECURITY {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专用调度系统 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_SUPERNOVADISPATCH {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_SUPERNOVADISPATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 supernova 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_SUPERNOVADISPATCH_SETTINGNAME {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_SUPERNOVADISPATCH_SETTINGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频监控系统 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_VIDEOMONIT {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_VIDEOMONIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位系统 的本地化字符串。
        /// </summary>
        internal static string IDS_SUBSYSTEM_WIPOS {
            get {
                return ResourceManager.GetString("IDS_SUBSYSTEM_WIPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户已存在于当前组中！ 的本地化字符串。
        /// </summary>
        internal static string IDS_USEREXISTSINGROUP_CONTNET {
            get {
                return ResourceManager.GetString("IDS_USEREXISTSINGROUP_CONTNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户已存在 的本地化字符串。
        /// </summary>
        internal static string IDS_USEREXISTSINGROUP_TITLE {
            get {
                return ResourceManager.GetString("IDS_USEREXISTSINGROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon inbound_call {
            get {
                object obj = ResourceManager.GetObject("inbound_call", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon inbound_call_failed {
            get {
                object obj = ResourceManager.GetObject("inbound_call_failed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap inbound_failed {
            get {
                object obj = ResourceManager.GetObject("inbound_failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap inbound_succeeded {
            get {
                object obj = ResourceManager.GetObject("inbound_succeeded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ips_device {
            get {
                object obj = ResourceManager.GetObject("ips_device", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon main_setting {
            get {
                object obj = ResourceManager.GetObject("main_setting", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Map_Marker_Ball_Chartreuse {
            get {
                object obj = ResourceManager.GetObject("Map_Marker_Ball_Chartreuse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Marker_Flag__Left_Pink {
            get {
                object obj = ResourceManager.GetObject("Marker_Flag__Left_Pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap marker_red {
            get {
                object obj = ResourceManager.GetObject("marker_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon message {
            get {
                object obj = ResourceManager.GetObject("message", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon message_go {
            get {
                object obj = ResourceManager.GetObject("message_go", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap micphone {
            get {
                object obj = ResourceManager.GetObject("micphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap navigate_down {
            get {
                object obj = ResourceManager.GetObject("navigate_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap navigate_left {
            get {
                object obj = ResourceManager.GetObject("navigate_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap navigate_up {
            get {
                object obj = ResourceManager.GetObject("navigate_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap next_page {
            get {
                object obj = ResourceManager.GetObject("next_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon outbound_call {
            get {
                object obj = ResourceManager.GetObject("outbound_call", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon outbound_call_failed {
            get {
                object obj = ResourceManager.GetObject("outbound_call_failed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap outbound_failed {
            get {
                object obj = ResourceManager.GetObject("outbound_failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap outbound_succeeded {
            get {
                object obj = ResourceManager.GetObject("outbound_succeeded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap plus_64 {
            get {
                object obj = ResourceManager.GetObject("plus_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap preferences_system {
            get {
                object obj = ResourceManager.GetObject("preferences_system", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap private_group {
            get {
                object obj = ResourceManager.GetObject("private_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap public_group {
            get {
                object obj = ResourceManager.GetObject("public_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rec {
            get {
                object obj = ResourceManager.GetObject("rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rec_on {
            get {
                object obj = ResourceManager.GetObject("rec_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap shortcuts {
            get {
                object obj = ResourceManager.GetObject("shortcuts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap speaker {
            get {
                object obj = ResourceManager.GetObject("speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap status_offline {
            get {
                object obj = ResourceManager.GetObject("status_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap status_online {
            get {
                object obj = ResourceManager.GetObject("status_online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon system_status {
            get {
                object obj = ResourceManager.GetObject("system_status", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap telephone_receiver {
            get {
                object obj = ResourceManager.GetObject("telephone_receiver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Trinno_Link {
            get {
                object obj = ResourceManager.GetObject("Trinno_Link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon user_call_from {
            get {
                object obj = ResourceManager.GetObject("user_call_from", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon user_call_to {
            get {
                object obj = ResourceManager.GetObject("user_call_to", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon user_customized {
            get {
                object obj = ResourceManager.GetObject("user_customized", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap user_inbound_call {
            get {
                object obj = ResourceManager.GetObject("user_inbound_call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap user_outbound_call {
            get {
                object obj = ResourceManager.GetObject("user_outbound_call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap warning_48 {
            get {
                object obj = ResourceManager.GetObject("warning_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
