//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace renstech.NET.SupernovaDispatcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("superadmin")]
        public string superadmin {
            get {
                return ((string)(this["superadmin"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("134")]
        public string UserInfoButtonWidth {
            get {
                return ((string)(this["UserInfoButtonWidth"]));
            }
            set {
                this["UserInfoButtonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string UserInfoButtonHeight {
            get {
                return ((string)(this["UserInfoButtonHeight"]));
            }
            set {
                this["UserInfoButtonHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ChannelButtonTopInfoFontSize {
            get {
                return ((int)(this["ChannelButtonTopInfoFontSize"]));
            }
            set {
                this["ChannelButtonTopInfoFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int ChannelButtonBottomInfoFontSize {
            get {
                return ((int)(this["ChannelButtonBottomInfoFontSize"]));
            }
            set {
                this["ChannelButtonBottomInfoFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int GroupButtonWidth {
            get {
                return ((int)(this["GroupButtonWidth"]));
            }
            set {
                this["GroupButtonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dispathcer.cfg")]
        public string ConfigFileName {
            get {
                return ((string)(this["ConfigFileName"]));
            }
            set {
                this["ConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recordings")]
        public string RecordingFileDir {
            get {
                return ((string)(this["RecordingFileDir"]));
            }
            //此处添加Set块，在系统加载配置时，从配置文件读取文件位置，并进行设置
            set { this["RecordingFileDir"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sharpua.exe")]
        public string HandsetUAFile {
            get {
                return ((string)(this["HandsetUAFile"]));
            }
            set {
                this["HandsetUAFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("callhistory.lst")]
        public string CallHistoryFile {
            get {
                return ((string)(this["CallHistoryFile"]));
            }
            set {
                this["CallHistoryFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("general")]
        public string SettingNameGeneral {
            get {
                return ((string)(this["SettingNameGeneral"]));
            }
            set {
                this["SettingNameGeneral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rings")]
        public string RingingFileDir {
            get {
                return ((string)(this["RingingFileDir"]));
            }
            set {
                this["RingingFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string AdminUserName {
            get {
                return ((string)(this["AdminUserName"]));
            }
            set {
                this["AdminUserName"] = value;
            }
        }
    }
}
